name: Auto PR to main from development branches

on:
  push:
    branches:
      - development1
      - development2

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get last commit message
        id: get_commit
        run: |
          echo "msg<<EOF" >> $GITHUB_OUTPUT
          echo "$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: main
          pr_title: ${{ steps.get_commit.outputs.msg }}
          pr_body: ${{ steps.get_commit.outputs.msg }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
